### ISSUE TITLE
The html-to-text causes performance issue

### ISSUE THREAD

**Issue by NoahDragon** [willin/hexo-wordcount#10]
Thanks for this great plugin.

Recently we found it causes some performance issue. We have a website with around 200 posts, normally it takes 1 mins to generate, however, after installed the hexo-wordcount, it needs more than 7 mins to generate.

After run nodejs profiler and analysis the result, we figure out one package in node causing the issue, it is the html-to-text, and it is the wordcount dependency. So we tried to remove the hexo-wordcount, the issue resolved.

Could you please take a look at this? Please let me know if you need more information.

**Comment by willin** [comment]
if there is a better package can replace it, pr welcome.

i've tried a site with more than 100,000,000 words and about 1,500 posts. 
only takes 57s to generate.  so i guess it herhaps depents on your cpu performance.

**Comment by ivan-nginx** [comment]
@NoahDragon [hexo-symbols-count-time](https://github.com/theme-next/hexo-symbols-count-time). No deps. Welcome.

**Comment by Lizhooh** [comment]
看了最新版的实现，去除了 `html-to-text`，300 篇文章，部署时要跑 3 分钟左右。

------
Read the latest version of the implementation, removed `html-to-text`, 300 articles, about 3 minutes to deploy.
