### ISSUE TITLE
文章字数统计不可以用

### ISSUE THREAD

**Issue by mapxn** [willin/hexo-wordcount#11]
文章字数统计和阅读时间不可用，全部显示0字，1分钟。但是全站总字体数可以。

**Comment by willin** [comment]
pls provide detailed info

**Comment by mapann** [comment]
该插件又什么依赖吗？
我卸载了`hexo-renderer-marked`插件
更换为 `hexo-renderer-kramed`
另外
我把`hexo-generator-index`卸载了
把archive的生成目录修改到`根目录`。
这样主页就变成了原来的archives页面。

我安装了`hexo-abbrlink`插件，对生成的URL固定化。
--·

上述某些行为可能会对本插件有影响。

**Comment by mapann** [comment]
本地测试`总字数统计 TotalCount`有效，新建文章后，总字数会增加

**Comment by willin** [comment]
我不知道是不是 hexo-renderer-kramed 引起的。 因为已经好久没用 hexo 了，并不太清楚现在更新后的版本对于以前插件有什么特殊要求没有

**Comment by willin** [comment]
试试 6.x 版本是否还有相同问题？
