### ISSUE TITLE
统计数据没有单位，建议加上，避免手工修改。

### ISSUE THREAD

**Issue by hawkinchina** [willin/hexo-wordcount#12]
统计数据没有单位，建议加上，避免手工修改。
 例如：字数统计: 456 字 |  阅读时长 ≈ 2 分钟

**Comment by willin** [comment]
字数单位：字，阅读时长单位：分（分钟）

根据实际需要进行使用，不放在函数内的主要原因是考虑到国际化需要。 比如英文翻译为：min。

这样就会使这个插件变得臃肿。所以虽然在使用的时候需要手动调整布局和翻译，但应该还算可以接受。
