### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by ghostsf** [willin/hexo-wordcount#13]
TypeError: (intermediate value)(intermediate value)(intermediate value)(...).replace is not a function
    at Object._ctx.post_template.render (eval at precompile (/xxx/node_modules/swig-templates/lib/swig.js:537:13), <anonymous>:186:950)
    at Object.eval [as tpl] (eval at precompile (/xxx/node_modules/swig-templates/lib/swig.js:537:13), <anonymous>:774:1078)

-------------------

可能是某篇文章有问题（因为都删掉，只留某一篇文章，就没问题），但是文章太多了.....

这个报错能发现什么问题吗？

**Comment by willin** [comment]
你发错地方了吧。。。这个插件没有依赖项。

swig-templates是什么我没听过。。。

**Comment by ghostsf** [comment]
@willin ？，hexo theme用的啊。装了hexo-wordcount这个插件才出现这个问题的，不装就没问题。有点奇怪

**Comment by ghostsf** [comment]
@willin 

> "hexo-wordcount": "^6.0.1",

`hexo version`

> hexo: 3.8.0
> hexo-cli: 1.1.0
> os: Darwin 18.5.0 darwin x64
> node: 11.12.0
> v8: 7.0.276.38-node.18
> uv: 1.26.0
> zlib: 1.2.11
> brotli: 1.0.7
> ares: 1.15.0
> modules: 67
> nghttp2: 1.34.0
> napi: 4
> llhttp: 1.1.1
> http_parser: 2.8.0
> openssl: 1.1.1b
> cldr: 34.0
> icu: 63.1
> tz: 2018e
> unicode: 11.0

**Comment by ghostsf** [comment]
貌似是这个主题的问题 hexo-theme-next ...
[https://github.com/theme-next/hexo-theme-next/issues/544](https://github.com/theme-next/hexo-theme-next/issues/544)
