### ISSUE TITLE
在.jsx如何实现

### ISSUE THREAD

**Issue by newusername2022** [willin/hexo-wordcount#15]
我用的是icarus，请问在.jsx怎么用`totalcount(site)`啊

**Comment by willin** [comment]
主题包链接发我看看

**Comment by newusername2022** [comment]
[https://github.com/ppoffice/hexo-theme-icarus](https://github.com/ppoffice/hexo-theme-icarus)
感谢

**Comment by willin** [comment]
文章计数：


https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.jsx#L21 

修改这个文件，先把 page 的内容都列出来看一下。


然后加在这个附近的位置：

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/article.jsx#L46

**Comment by willin** [comment]
站点计数， site字段参考这个位置：

https://github.com/ppoffice/hexo-theme-icarus/blob/master/layout/common/widgets.jsx#L62

来获取，放到你想要的位置。

p.s. 封装的函数应该是被加在 `helper` 里了，比如全局计数方法名应该是 `helper.totalcount`

**Comment by newusername2022** [comment]
[https://github.com/ppoffice/hexo-theme-icarus/blob/d74488ac96ebc14374cac1aa10ac71b39ca8175b/layout/widget/profile.jsx#L74](https://github.com/ppoffice/hexo-theme-icarus/blob/d74488ac96ebc14374cac1aa10ac71b39ca8175b/layout/widget/profile.jsx#L74)
👆我准备在这行后面加，但得到了
` Cannot read property 'totalcount' of undefined`
这个错误，应该是没有require wordcount的packge？
我试着在
[https://github.com/ppoffice/hexo-theme-icarus/blob/d74488ac96ebc14374cac1aa10ac71b39ca8175b/layout/widget/profile.jsx#L1](https://github.com/ppoffice/hexo-theme-icarus/blob/d74488ac96ebc14374cac1aa10ac71b39ca8175b/layout/widget/profile.jsx#L1)
这里加上`const { Component } = require('inferno', 'hexo-wordcount');`
，但还是同样的错误

**Comment by willin** [comment]
没见过你这样的写法。

**Comment by willin** [comment]
参考： https://github.com/ppoffice/hexo-theme-icarus/blob/d74488ac96ebc14374cac1aa10ac71b39ca8175b/layout/widget/profile.jsx#L96-L117

这个插件的方法应该是会被注册到 helper 里。
