### ISSUE TITLE
如何添加站点总阅读时长

### ISSUE THREAD

**Issue by SnowMeteors** [willin/hexo-wordcount#16]
我想在hexo里面的站点显示，站点总阅读时长，请问如何实现？

**Comment by willin** [comment]
没有该功能，这个需要读取所有文章的具体内容。才能计算出来，非常损耗 build 性能

**Comment by SnowMeteors** [comment]
> 没有该功能，这个需要读取所有文章的具体内容。才能计算出来，非常损耗 build 性能

还有一个问题，我想让一个单独的文章，不添加阅读时长和字数统计，是否能在md上面添加wordcount:false 这类的

**Comment by willin** [comment]
以 Next 主题为例： https://github.com/iissnan/hexo-theme-next/blob/master/layout/_macro/post.swig#L223


参考代码： 

```swig
 {% if not post.hide_wordcount %}
  // 包裹原有 template
 {% endif %}
```

文章里的 meta 信息：

```yaml
title: xxxx
hide_wordcount: true
```
