### ISSUE TITLE
min2read 閱讀時長最低應為1分鐘

### ISSUE THREAD

**Issue by gasolin** [willin/hexo-wordcount#3]
使用min2read來估計閱讀時長, 目前當低於300字時會回傳 0 (分鐘), 
而實際上不管文章多短, 閱讀還是要花一些時間. 

hexo-reading-time 會將回傳值不足一分鐘的改成 1 分鐘
https://github.com/ierhyna/hexo-reading-time/blob/master/lib/readingtime.js

**Comment by gasolin** [comment]
@willin 麻煩你release 2.0.1, 這樣其他人才用得上:)

**Comment by willin** [comment]
@gasolin 我在考慮如何優化閱讀時間的計算，我看到鏈接上 wpm 的默認值是150，當時我設置中文300英文160只是一個接近我個人閱讀水平的近似值，但近期發現不同的文章可能這個閱讀預計非常不準確。需要再做一些調整優化。

**Comment by gasolin** [comment]
@willin 也许先可以做的是开放让使用者调整中英文wpm参数?

ex: 
`min2read(page.content, {'en': 150, 'zh': 300})` 

dict 里找不到的就用默认值代替
