### ISSUE TITLE
Bug with Arabic language.

### ISSUE THREAD

**Issue by ivan-nginx** [willin/hexo-wordcount#7]
1. Go on [test post](http://test.almostover.ru/arabic-rtl-test/).
2. See **Words count in article: 10** in meta. There are more then 10 words in this article, i think.
3. See other articles on this site — other posts in normal counting state.

So, bug with RTL language counting.

**Comment by willin** [comment]
https://github.com/willin/hexo-wordcount/blob/master/index.js#L11-L12

currently it can only counts chinese/english words.

notice that L11: 

```js
var cn = content.match(/[\u4E00-\u9FA5]/g) || [];
```

means chinese words unicode range.  you can change it into arabic language range.

**Comment by ivan-nginx** [comment]
@willin but [Russian words counting too](https://almostover.ru/). They also have another unicode instead of Chinese, isn't it?
***
Oooh, i see. U added filter in function and only CN and EN will work with your latest plugin version?

**Comment by willin** [comment]
yes.  

yes.

**Comment by ivan-nginx** [comment]
Ok, i got it. Bad. Very bad and sad. Need to do for international support, not only for some countries.

**Comment by willin** [comment]
as you wish, i will support asap

**Comment by willin** [comment]
@ivan-nginx  do me a favor

```
كل فمرّ وانتهاءً حين. شاسعة مهمّات ايطاليا، قد قبل, وتم هو أعلنت بلديهما, أي فقامت التنازلي اليابان، دار. ثم ضمنها الإمتعاض بريطانيا-فرنسا على, قد حول وقرى استدعى. أوروبا ألمانيا ٣٠ يبق. عرض إذ احداث الصين. في بين ببعض ويكيبيديا،, وصل بسبب تحرير النفط بـ. 
```

is it 44 words ( 212 chars )?

ckeditor wordcount: <http://w8tcha.github.io/CKEditor-WordCount-Plugin/>

**Comment by ivan-nginx** [comment]
@willin i don't know Arabic language, it seems like something about 40 words, yep. But not 10 words anyway, u agree?
I repeat: for now on my test site version WC 2.x installed (without CN/EN filtering) and RU lang work fine. Only RTL for now not working as we see.

RU/EN/CN have LTR language direction, instead of Arabic language, wich have RTL direction. I added RTL direction feature in [last pull](https://github.com/iissnan/hexo-theme-next/pull/1697) (**PART 4**) before [release 5.1.2 NexT version](https://github.com/iissnan/hexo-theme-next/releases).

BTW, your wordcount plugin [was integrated in NexT](https://github.com/iissnan/hexo-theme-next/pull/1381) (**PART 3**) by me too, so, i don't understand why u try to isolate plugin in CN/EN language filters. NexT support many languages, Hexo support i18n. And your integrated plugin already translated in NexT, but u adding filter only on some languages. I think, this is not right to great coding. And i believe on your correction about freedom of choice.

**Comment by willin** [comment]
i see

i will try to look deep into this issue before weekend

**Comment by willin** [comment]
try beta version

### Count Words

```js
countwords(post.content)
```

### Count Chars

```js
countchars(post.content)
```
